### ISSUE TITLE
Sound script

### ISSUE THREAD

**Issue by Breizil29** [archusXIV/wm_config#6]
Hello @archusXIV I use some of your configuration files including "autostart" and I use pipewire instead pulseaudio and I would like you to help me to make the "sound" script work with "pamixer"

1. `# Sound
2. DEFAULT_SINK=$(pamixer --get-volume)
3. pamixer --set-volume "${DEFAULT_SINK}" 50`

in terminal : "pamixer --set-volume 50" >> works

**Comment by archusXIV** [comment]
hi, pamixer is a pulseaudio tool... is pactl works too?
Maybe if you install some compatibility tool from pipewire to pulseaudio
https://archlinux.org/packages/extra/x86_64/pamixer/
https://archlinux.org/packages/extra/x86_64/pipewire-pulse/

**Comment by Breizil29** [comment]
```
[14:41:06]  gg  on ArchLinux ~/.local/bin
➜ ./autostart
```

**Comment by archusXIV** [comment]
`DEFAULT_SINK=$(pactl get-default-sink)`

This is to **get** the default output channel on the sound card

#DEFAULT_SINK=$(pamixer --get-volume)

This is to get the actual volume, **not** the default channel
Try to get the right channel with

`pamixer --list-sinks`

then
`pamixer --sink INDEX`

where INDEX is your default

`DEFAULT_SINK=$(pamixer --sink INDEX)`

`pamixer --set-volume "${DEFAULT_SINK}" 50`

Sorry if I'm wrong but I don't use pamixer and please don't post in the issue section because this is not my mistake or a config issue either, thanks, I hope you will find out.
regards

**Comment by Breizil29** [comment]
Sorry for posting in the issue section.
Thank you for your help.
Don't hesitate to delete this post.

**Comment by Breizil29** [comment]
Sorry for posting in the issue section.
Thank you for your help.
Don't hesitate to delete this post.
